---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-local-volume
  labels:
    directory: data
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /mnt/sda/uptime-kuma/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-rspi4
          - worker01-rspi4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-local-claim
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
        name: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1
        imagePullPolicy: Always
        ports:
          - containerPort: 3001
        volumeMounts:
        - name: uptime-kuma-local-volume
          mountPath: "/app/data"
      volumes:
      - name: uptime-kuma-local-volume
        persistentVolumeClaim:
          claimName: uptime-kuma-local-claim
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-web
spec:
  selector:
    app: uptime-kuma
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  externalIPs:
  - 10.0.0.100
  - 10.0.0.101
